# Generated by Django 4.1.7 on 2023-04-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_log_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='points',
            field=models.IntegerField(),
        ),
    ]
